services:
  - type: web
    name: openhands-app
    env: docker
    docker:
      image: docker.all-hands.dev/all-hands-ai/openhands:0.41
      pull:
        policy: always
    envVars:
      - key: SANDBOX_RUNTIME_CONTAINER_IMAGE
        value: docker.all-hands.dev/all-hands-ai/runtime:0.41-nikolaik
      - key: LOG_ALL_EVENTS
        value: "true"
    plan: free
    numInstances: 1
    region: oregon
    build:
      rootDir: /
    healthCheck:
      path: /
      enable: true
    disk:
      name: openhands-state
      mountPath: /.openhands-state
    ports:
      - port: 3000
        envVarName: PORT
        envVarValue: 3000