services:
  - type: web
    name: openhands-app
    dockerfilePath: Dockerfile
    envVars:
      - key: SANDBOX_RUNTIME_CONTAINER_IMAGE
        value: docker.all-hands.dev/all-hands-ai/runtime:0.41-nikolaik
      - key: LOG_ALL_EVENTS
        value: "true"
    plan: free
    numInstances: 1
    region: oregon
    disk:
      name: openhands-state
      mountPath: /.openhands-state
    env:
      - key: PORT
        value: 3000