services:
  - type: web
    name: openhands-app
    # Remove dockerfilePath since we're using a pre-built image; configure image in dashboard
    envVars:
      - key: SANDBOX_RUNTIME_CONTAINER_IMAGE
        value: docker.all-hands.dev/all-hands-ai/runtime:0.41-nikolaik
      - key: LOG_ALL_EVENTS
        value: "true"
      - key: PORT
        value: "3000" # Ensure value is a string
    plan: free
    numInstances: 1
    region: oregon
    disk:
      name: openhands-state
      mountPath: /.openhands-state